version: '3'

services: 
    app:
        container_name: app
        image: nginx:stable
        ports: 
            - "8080:80"
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html
            - ./nginx/logs:/var/log/nginx
        
    phpfpm:
        container_name: phpfpm
        build: ./Dockerfiles/phpfpm
        volumes: 
            - ./src:/var/www/html
        ports: 
            - "9000:9000"

    mysql:
        container_name: mysql
        image: mysql:5.7.30
        environment: 
            MYSQL_DATABASE: magento
            MYSQL_USER: myuser
            MYSQL_PASSWORD: abc123
            MYSQL_ROOT_PASSWORD: abc123
        ports: 
            - "3306:3306"

    elasticsearch:
        image: elasticsearch:7.8.0
        ports: 
            - "9300:9300"
            - "9200:9200"
        environment: 
            discovery.type: single-node

        

     
